

### curl request
/*
curl -X POST http://localhost:8081/api/v1/auth/login \
  -H "Content-Type: application/json" \
  -d '{
    "phoneNumber": "1234567890"
  }'
*/
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
    "phoneNumber": "1234567890"
  }

